---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kafka-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      volumes:
        - name: kafka-volume
          persistentVolumeClaim:
            claimName: kafka-volume
      nodeSelector:
        node-type: name_space
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: ['sh', '-c', 'until nc -z zookeeper 2181; do echo "waiting for zookeeper"; sleep 5; done']
        - name: wait-extra
          image: busybox
          command: ['sh', '-c', 'echo "Waiting an additional 3 minutes"; sleep 180']
      containers:
        - name: kafka-service
          image: container_registry/kafka-server_environment-name_space:build_id
          envFrom:
          - secretRef:
              name: kafka-config-secrets
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 19092
              protocol: TCP
            - containerPort: 29092
              protocol: TCP
          # resources:
          #   requests:
          #     memory: '2024Mi'
          #     cpu: '0.5'
          #   limits:
          #     memory: '9Gi'
          #     cpu: '1'       
          volumeMounts:
            - name: kafka-volume
              mountPath: /var/lib/kafka/data

